# Generated by Django 5.0.2 on 2024-11-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('agent_first_name', models.CharField(max_length=255)),
                ('agent_last_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('amenity_type', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'amenity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=255)),
                ('floor_area', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('venue_type', models.CharField(max_length=255)),
                ('floor', models.IntegerField()),
                ('under_renovation', models.BooleanField(null=True)),
                ('reservation_fee', models.IntegerField()),
            ],
            options={
                'db_table': 'venue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_middle_initial', models.CharField(blank=True, max_length=2, null=True)),
                ('customer_last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberAssignment',
            fields=[
                ('member_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'memberassignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('number_of_participants', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentBuilding',
            fields=[
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='reservations.agent')),
            ],
            options={
                'db_table': 'agentbuilding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmenityVenue',
            fields=[
                ('amenity', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='reservations.amenity')),
            ],
            options={
                'db_table': 'amenityvenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvailableVenue',
            fields=[
                ('a_venue', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='reservations.venue')),
            ],
            options={
                'db_table': 'availablevenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnavailableVenue',
            fields=[
                ('u_venue', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='reservations.venue')),
                ('renovation_date_start', models.DateField()),
                ('renovation_date_end', models.DateField()),
            ],
            options={
                'db_table': 'unavailablevenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VenueBuilding',
            fields=[
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='reservations.venue')),
            ],
            options={
                'db_table': 'venuebuilding',
                'managed': False,
            },
        ),
    ]
